- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/CompilerApiExtensions.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/analysis/CompilationUnitDependenciesTest.scala
> Treat locally defined types properly

- org.scala-refactoring.library/.classpath
- org.scala-refactoring.library/pom.xml
- org.scala-refactoring.library/src/main/scala-2_10/README
- org.scala-refactoring.library/src/main/scala-2_11/README
- pom.xml
This pull request introduces proper support for multiple Scala versions into the build process.
> Support multiple scala versions

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
Fixes [#1002498](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002498)
>  Don't reorder modifiers already defined in the original source

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/package.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/tracing.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/CustomFormattingTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/IndividualSourceGenTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/PrettyPrinterTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceGenTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
There is an associated PR to scala-ide which should be merged first to avoid compilation failures: https://github.com/scala-ide/scala-ide/pull/979
> Support writing trace output to files and remove unused imports

- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/analysis/CompilationUnitDependenciesTest.scala
This test was recently suggested by @sschaef.
> Add a test that makes sure that language feature imports are not removed

- patch-ide.bash
- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitIndexes.scala
- src/main/scala/scala/tools/refactoring/analysis/GlobalIndexes.scala
- src/main/scala/scala/tools/refactoring/analysis/SymbolExpanders.scala
- src/main/scala/scala/tools/refactoring/common/PositionDebugging.scala
- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/MoveClassTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/extraction/ExtractValueTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsFullyRecomputeTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeMissingImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
__This PR contains several parts:__
1. A fix for  [Ticket #1002371](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002371#/activity/ticket:)
2. Improved tracing output
3. Unit tests that deal with broken Scala code now fail unless explicitly marked as such
4. A script for conveniently patching the IDE with a local build of the library
Details can be found in the commit messages.
> Various changes and a fix for #1002371

- src/test/scala/scala/tools/refactoring/tests/sourcegen/ReusingPrinterTest.scala
This reverts commit 83f8a28e3bba5997408deb801d280fd00da20ded.
Fixes #69
---------
Took me a long preparation time to revert this commit from nearly a year ago. Actually, it took me just 10 seconds, but do not tell anyone...
> Revert "Don't call symbol.isLazy in test suite"

- build.sbt
- pom.xml
- project/build.sbt
- src/main/scala/scala/tools/refactoring/analysis/Indexes.scala
- src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala
- src/main/scala/scala/tools/refactoring/implementations/EliminateMatch.scala
- src/main/scala/scala/tools/refactoring/sourcegen/Layout.scala
- src/main/scala/scala/tools/refactoring/sourcegen/LayoutHelper.scala
- src/main/scala/scala/tools/refactoring/sourcegen/TreeChangesDiscoverer.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
Some more fixes needed to get the sbt build warning free.
> Update sbt build

- src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala
- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/main/scala/scala/tools/refactoring/sourcegen/SourceGenerator.scala
- src/main/scala/scala/tools/refactoring/sourcegen/TreeChangesDiscoverer.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
Fixes [#1002609](https://www.assembla.com/spaces/scala-ide/simple_planner#/ticket:1002609)
> Correctly set positions for selects involving package objects

- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
Fixes [#1002626](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002626).
> Be more careful when removing unneeded imports

- src/main/scala/scala/tools/refactoring/Refactoring.scala
- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitIndexes.scala
- src/main/scala/scala/tools/refactoring/analysis/GlobalIndexes.scala
- src/main/scala/scala/tools/refactoring/analysis/ImportAnalysis.scala
- src/main/scala/scala/tools/refactoring/analysis/PartiallyAppliedMethodsFinder.scala
- src/main/scala/scala/tools/refactoring/common/EnrichedTrees.scala
- src/main/scala/scala/tools/refactoring/common/Selections.scala
- src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- src/main/scala/scala/tools/refactoring/implementations/ImportsHelper.scala
- src/main/scala/scala/tools/refactoring/implementations/MarkOccurrences.scala
- src/main/scala/scala/tools/refactoring/implementations/MethodSignatureRefactoring.scala
- src/main/scala/scala/tools/refactoring/implementations/UnusedImportsFinder.scala
- src/main/scala/scala/tools/refactoring/sourcegen/AbstractPrinter.scala
- src/main/scala/scala/tools/refactoring/sourcegen/LayoutHelper.scala
- src/main/scala/scala/tools/refactoring/sourcegen/PrettyPrinter.scala
- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/main/scala/scala/tools/refactoring/sourcegen/SourceGenerator.scala
- src/main/scala/scala/tools/refactoring/sourcegen/TreeChangesDiscoverer.scala
- src/main/scala/scala/tools/refactoring/sourcegen/TreePrintingTraversals.scala
- src/main/scala/scala/tools/refactoring/transformation/TreeFactory.scala
- src/main/scala/scala/tools/refactoring/transformation/TreeTransformations.scala
- src/test/scala/scala/tools/refactoring/tests/RefactoringTestSuite.scala
- src/test/scala/scala/tools/refactoring/tests/common/PimpedTreesTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/PrettyPrinterTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceGenTest.scala
> Rename PimpedTrees to EnrichedTrees

- src/main/scala/scala/tools/refactoring/analysis/SymbolExpanders.scala
Consider remark from @wpopielarski in #156.
> Cosmetics for #156

- .classpath
- build.sbt
- src/main/scala-2_10/scala/tools/refactoring/implementations/oimports/ImplicitValDefTraverserPF.scala
- src/main/scala-2_11/scala/tools/refactoring/implementations/oimports/ImplicitValDefTraverserPF.scala
- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/main/scala/scala/tools/refactoring/analysis/ImportsToolbox.scala
- src/main/scala/scala/tools/refactoring/analysis/IsNotInImports.scala
- src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/NotPackageImportParticipants.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/Region.scala
- src/test/scala-2.10/README
- src/test/scala-2.10/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsWithMacrosTest.scala
- src/test/scala-2.11/README
- src/test/scala-2.11/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsWithMacrosTest.scala
- src/test/scala/scala/tools/refactoring/tests/RefactoringTestSuite.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
Contains some enhancements for imports organizing
> Adds enhancements to organize imports working

- src/main/scala/scala/tools/refactoring/common/TracingHelpers.scala
- src/main/scala/scala/tools/refactoring/implementations/MarkOccurrences.scala
- src/test/java/scala/tools/refactoring/common/TracingHelpersTest.scala
- src/test/scala/scala/tools/refactoring/tests/RefactoringTestSuite.scala
These improvements to the debug output have been implemented in connection with https://github.com/scala-ide/scala-ide/pull/1106, but they should be generally useful.
> Improve debug output

- src/main/scala-2_11/scala/tools/refactoring/implementations/oimports/TreeToolboxScanners.scala
- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/ImportsOrganizer.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/NotPackageImportParticipants.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/Region.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/RegionTransformations.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/TreeToolbox.scala
- src/test/scala-2.11/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsScalaSpecificTests.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
This PR adds some failing scenarios shown in newly added bulk of tests.
> Adds improvements in organize imports. See added tests.

- src/main/scala/scala/tools/refactoring/implementations/MoveClass.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/MoveClassTest.scala
This PR is meant to take care of [#1002761](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002761) and [#1002785](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002785).
> Fix some issues with `MoveClass`

- build.sbt
- project/build.properties
> clean up the sbt files for community build

- src/main/scala/scala/tools/refactoring/transformation/TreeTransformations.scala
fix for change in behaviour of https://github.com/scala/scala/pull/5330
> fixes import tests

- src/test/java/scala/tools/refactoring/tests/util/ScalaVersionTestRule.java
- src/test/scala/scala/tools/refactoring/tests/implementations/ExplicitGettersSettersTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/PrettyPrinterTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceGenTest.scala
Consult https://github.com/scala-ide/scala-refactoring/issues/180 for background information.
> Disable several tests for Scala-2.12.1

- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsGroupsTest.scala
Adds * for default imports group. Intended to solve https://github.com/scala-ide/scala-refactoring/issues/192
> Default imports grouping
