- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/transformation/TreeFactory.scala
Create the TermName instance explicitly, because the implicit is deprecated.
> Explicit creation of TermName

- org.scala-refactoring.library/.classpath
- org.scala-refactoring.library/pom.xml
- org.scala-refactoring.library/src/main/scala-2_10/README
- org.scala-refactoring.library/src/main/scala-2_10/scala/tools/refactoring/ScalaVersionsAdapter.scala
- org.scala-refactoring.library/src/main/scala-2_11/README
- org.scala-refactoring.library/src/main/scala-2_11/scala/tools/refactoring/ScalaVersionsAdapter.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/util/CompilerProvider.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/analysis/CompilationUnitDependenciesTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/MoveClassTest.scala
- pom.xml
This pull request should improve the annotation handling by the implementation of "Organize Imports", by not only processing `AnnotationInfo.original`, but also `AnnotationInfo.tree`. As the latter is only available with Scala-2.11, this request is based on #76, which should be merged first. You might also want to take a look at [Assembla Ticket 1001726](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1001726-organise-imports-and-scalatest-with-junitrunner-don-t-like-each-other) and  [Assembla Ticket 1001793](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1001793-organize-imports-removes-import-referenced-from-an-annotation).
> Improves annotation handling for "Organize Imports"

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/Selections.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
This should fix [Ticket 1002392](https://www.assembla.com/spaces/scala-ide/tickets/1002392-rename-refactoring-breaks-with-lazy-vals#/activity/ticket:).
Note that I think that this fix is kind of a hack, since `DefDef.mods.positions` should be set by the compiler, not by us, so we might want to discuss this further...
> Fix renaming for lazy vals

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/analysis/CompilationUnitDependenciesTest.scala
Note that once again the problem is that positions are not set properly. I've worked around this by adding a special case for lazy `ValDef`s. Maybe we should also discuss this with the people writing the compiler so that they can fix their code...
Fixes [#1002402](https://www.assembla.com/spaces/scala-ide/tickets/1002402-organize-imports-removes-import-referenced-by-lazy-val#/activity/ticket:)
> Properly handle type annotations on lazy vals when organizing imports

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/Change.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/analysis/MultipleFilesIndexTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/util/TestRefactoring.scala
Add a new `scala.tools.refactoring.common.Change` for rename operations
`scala.tools.refactoring.tests.util.TestHelper` now supports testing for rename operations
Code cleanups
Fixes [#1001928](https://www.assembla.com/spaces/scala-ide/tickets/1001928#/activity/ticket:) in connection with an associated update for the IDE
> Take care of file rename operations in `rename` refactorings

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
This commit fixes a bug in the implementation of
`Rename.prepare(s: Selection).isLocalRename(t: global.Tree)` that caused
`hasLocalScope` to be set for vals that might be accessed from other files.
Extend the test suite, so that we can explicitly check for `hasLocalScope`
Fixes #1002435 and #1002434
> Don't set `hasLocalScope` for public vals

- .gitignore
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/sourcegen/Requisite.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
This PR introduces my attempt to fix [Ticket 1002446](https://www.assembla.com/spaces/scala-ide/tickets/1002446#/activity/ticket:). Unfortunately there are still problems in connection with *lazy* vals (see https://github.com/mlangc/scala-refactoring/blob/rename-package-private-removes-access-modifiers-1002446/org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala#L1862), and I think also with *override*, but we might want to deal with these in separate tickets and PRs.
As for the code itself: The biggest addition of this PR are the utility classes `scala.tools.refactoring.util.SourceWithMarker` together with `scala.tools.refactoring.util.SourceWithMarker.Movement`. These classes are documented in the source and currently used in …
> Rename package private vals/defs with scoped access modifiers

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
Only emit one `RenameSourceFileChange` if a class is renamed together with its companion object.
Fixes [#1002490](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002490#/activity/ticket:)
> Don't emit duplicate "RenameSourceFileChanges"

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/implementations/ImportsHelper.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
Fixes [#1002506](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002506#/activity/ticket:) (actually only one line) and adds some trace messages.
> Don't import local symbols on "Organize Imports"

- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/Selections.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/implementations/ImportsHelper.scala
- org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/implementations/MoveClass.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/analysis/CompilationUnitDependenciesTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/implementations/MoveClassTest.scala
- org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
This PR is my first attempt to handle local imports properly when calculating dependencies. More details can be found in the commit messages/comments.
Fixes [#1002511](https://www.assembla.com/spaces/scala-ide/tickets/1002511)
Fixes [#1002512](https://www.assembla.com/spaces/scala-ide/tickets/1002512)
> Consider local imports when calculating dependencies of Scala code

- pom.xml
codehaus.org has been shut down, but their server isn't 404'ing,
instead, they're sending back invalid data, which maven sticks
in ~/.m2 as if nothing were wrong.
thus, the presence of this entry is breaking the build here, which
then causes the build scripts in the scala-ide/uber-build repo to
break, which in turn is breaking the scripts/jobs/integrate/ide script
in the scala/scala repo, which in turn means Scala PR validation is
broken
I tested this change locally by deleting my ~/.m2 directory and
running the build-2.11.sh and build-2.10.sh scripts. they both
succeeded, so apparently the repo entry isn't even needed.
> remove reference to non-existent repository

- build.sbt
It is not done automatically, therefore we do it manually.
> Include Manifest file in sbt build

- src/main/scala/scala/tools/refactoring/sourcegen/CommentsUtils.scala
- src/main/scala/scala/tools/refactoring/sourcegen/CommonPrintUtils.scala
- src/main/scala/scala/tools/refactoring/sourcegen/Indentation.scala
- src/main/scala/scala/tools/refactoring/sourcegen/Layout.scala
- src/main/scala/scala/tools/refactoring/sourcegen/LayoutHelper.scala
- src/main/scala/scala/tools/refactoring/sourcegen/PrettyPrinter.scala
- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/main/scala/scala/tools/refactoring/sourcegen/SourceGenerator.scala
- src/main/scala/scala/tools/refactoring/sourcegen/SourceUtils.scala
- src/main/scala/scala/tools/refactoring/sourcegen/TreePrintingTraversals.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/AddImportStatementTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceHelperTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceUtilsTest.scala
This PR, which is closely related to https://github.com/scala-ide/scala-refactoring/pull/93, deals mostly with `CommonPrintUtils.balanceBrackets` once more (details can be found in the commit messages). Please note that I still don't trust this function completely, as I don't understand what the `"\\"` in
```scala
f.asText.reverse.replaceFirst("\\" + close, ("" + close) * (opening - closing + 1)).reverse
```
(see https://github.com/mlangc/scala-refactoring/blob/organize-imports-adds-opening-parenthesis-1002088/src/main/scala/scala/tools/refactoring/sourcegen/CommonPrintUtils.scala#L61) is about. @misto Maybe you can clarify?
Last but not least, these changes fix [Ticket #1002088](https://www.assembla.com/spaces/scala-ide/tickets/1002088-automatic-import-adds-opening-parenthesis-if-a-string …
> Refactorings might mess with parens

- .gitignore
- src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
As outlined in [Ticket #1002540](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002540), the extraction of named arguments in `PimpedTrees.BlockExtractor.unapply.fixNamedArgumentCall` was overly simplistic, which led to tickets like [#1002540](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002540). This PR can be divided roughly into two parts: The first part is about extending the functionality around `SourceWithMarker`. The second part puts the new functionality into use by fixing `PimpedTrees.BlockExtractor.unapply.fixNamedArgumentCall`.
I'm well aware of the fact, that we wouldn't have to deal with these subtitles, if named parameters could be obtained from the ASTs. This topic has already been discussed, and I'm still planning to add this …
> Fix locating parameter assignments in argument lists

- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
This PR fixes [Ticket #1002560](https://www.assembla.com/spaces/scala-ide/tickets/1002560-rename-refactoring-removes-return-type). More information can be found in commit messages/comments.
> Don't remove return times on rename refactorings

- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
Fixes [Ticket #1002142](https://www.assembla.com/spaces/scala-ide/tickets/1002142-organize-imports-erroneously-creates-imports-for-_*#/activity/ticket:).
> Don't confuse `_*` with an ordinary type when organizing imports 

- src/main/scala/scala/tools/refactoring/implementations/ImportsHelper.scala
- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/main/scala/scala/tools/refactoring/transformation/TreeTransformations.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/AddImportStatementTest.scala
Fixes [#1002399](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002399-organize-imports-inserts-import-in-wrong-package-declaration). More details can be found in the comment that has been added to `TreeTransformations`.
> Don't add imports to the wrong package

- src/main/scala/scala/tools/refactoring/analysis/SymbolExpanders.scala
- src/main/scala/scala/tools/refactoring/common/Selections.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
This error was introduced in https://github.com/scala-ide/scala-refactoring/pull/78 although we discussed exactly this piece of code thoroughly ;-). Maybe there is compiler warning that would have pointed this out sooner?
Fixes [#1002569](https://www.assembla.com/spaces/scala-ide/tickets/1002569-renaming-lazy-constants-breaks-code#/activity/ticket:)
>  Fix a stupid error when setting modifier positions for lazy vals

- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
Fixes [#1002537](https://www.assembla.com/spaces/scala-ide/tickets/1002537-wrong-refactor--gt--rename-behavior/details#)
> Don't break imports when renaming objects

- src/main/scala/scala/tools/refactoring/common/Selections.scala
- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
Fixes [Ticket 1002502](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002502-rename-breaks-overriding-lazy-vals/details#). More details can be found in the comments.
> Don't break code when renaming lazy vals

- src/main/scala-2_10/scala/tools/refactoring/ScalaVersionsAdapter.scala
- src/main/scala-2_11/scala/tools/refactoring/ScalaVersionsAdapter.scala
- src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala
- src/main/scala/scala/tools/refactoring/sourcegen/Layout.scala
- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/main/scala/scala/tools/refactoring/util/CompilerProvider.scala
- src/main/scala/scala/tools/refactoring/util/Memoized.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/main/scala/scala/tools/refactoring/util/UniqueNames.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/AddFieldTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/AddMethodTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/AddImportStatementTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/UnusedImportsFinderTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
Fixes [#1002564](https://www.assembla.com/spaces/scala-ide/tickets/1002564-rename-refactoring-is-broken-in-case-the-renamed-method-has-default-arguments).
> Fix two problems with printing trees related to default arguments

- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/test/scala/scala/tools/refactoring/implementations/OrganizeImportsAlgosTest.scala
- src/test/scala/scala/tools/refactoring/tests/RefactoringTestSuite.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
Fixes [#1002526](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002526--quot-organize-imports-quot--duplicates-imports/details#). More details can be found in the commit messages.
>  Don't duplicate imports while grouping them

- patch-ide.bash
- src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala
- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
This PR contains a fix for [#1002611](https://www.assembla.com/spaces/scala-ide/tickets/1002611-rename-refactoring-breaks-when-default-arguments-and-comments-spaces-are-involved/details#), as well as some mostly cosmetic changes.
>  Consider exotic but legal places for comments and spaces

- src/main/scala/scala/tools/refactoring/sourcegen/LayoutHelper.scala
- src/main/scala/scala/tools/refactoring/sourcegen/PrettyPrinter.scala
- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/IndividualSourceGenTest.scala
Fixes [#1001932](https://www.assembla.com/spaces/scala-ide/tickets/1001932-refactoring-name-change-adds-extraneous-square-brackets/details#) and [#1002618](https://www.assembla.com/spaces/scala-ide/tickets/1002618-rename-class-breaks-code-in-generic-when-comments-spaces-are-involved/details#). More details can be found in the commit messages.
Note that I'm not sure if I'm happy with the last commit, that adds a tweak for a single test (that would still generate compiling code without it). I'd really like to hear your opinions on that!
>  Be more careful when printing type parameter lists

- src/main/scala/scala/tools/refactoring/sourcegen/ReusingPrinter.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
Fixes [#1002620](https://www.assembla.com/spaces/scala-ide/tickets/1002620-renaming-a-function-id-with-multi-line-parentheses/details#)
> Don't omit closing paren after rename operation

- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/test/scala/scala/tools/refactoring/tests/analysis/CompilationUnitDependenciesTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
This PR is mostly concerned with compilation unit dependency calculation and fixes [Ticket #1002613](https://www.assembla.com/spaces/scala-ide/tickets/1002613). I think that additional tweaks will be needed, so feel free to come up with test cases that fail with the current implementation ;-).
> Treat nested imports more carefully

- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
Organize Imports is not able to rearrange imports in blocks of
codes which are not top level package one. So it is not rearrange
following imports in snippet below:
```
package acme.foo
class Foo {
def foo() = {
import acme.ctes.Ctes.C
import acme.ctes.Ctes.{ B, A }
C + B + A
}
}
```
with this fix it should turn to:
```
package acme.foo
class Foo {
def foo() = {
import acme.ctes.Ctes.{ A, B }
import acme.ctes.Ctes.C
C + B + A
}
}
```
Fixes #1001078
> Fixes Organize Imports in non-package blocks

- src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
in case of
```
import scala.util.Try
class Test(val a: (Try[_], _))
```
the Organize Imports action removes `import scala.util.Try`.
For more found cases refer to tests.
fixes #1002621
> Prevents import removal for existential type

- src/main/scala/scala/tools/refactoring/implementations/InlineLocal.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/InlineLocalTest.scala
I don't know why it was disabled for private values, seems to be an
oversight to me.
Fixes #1002648
>  Enable inline refactoring for private values 

- src/main/scala/scala/tools/refactoring/sourcegen/SourceUtils.scala
- src/main/scala/scala/tools/refactoring/sourcegen/TreePrintingTraversals.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/AddImportStatementTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceUtilsTest.scala
This is a fix for [#1002619](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002619-overlapping-text-edits-on-code-completion/details#). It is a complicated fix, since the document is broken.
> Fix for t1002619

- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
This PR implements the rename refactoring without tree printing, as discussed in Krakow. The implementation is more or less strait forward, and I think that the rename refactoring should now be more solid then ever before. The only fly in the ointment is that named arguments are still a problem, but I plan to look into this in the near future, since it really bugs me. Implementing this has been a very rewarding experience, and we should definitely continue to work in this direction (that is avoiding AST printing wherever possible).
Fixes [#1002643](https://www.assembla.com/spaces/scala-ide/tickets/1002643), [#1002622](https://www.assembla.com/spaces/scala-ide/tickets/1002622), [#1001966](https://www.assembla.com/spaces/scala-ide/tickets/1001966) and probably many undocumented bugs more.
> Rename without tree printing

- META-INF/MANIFEST.MF
- build.sbt
See the ticket for a discussion about why we need this.
Fixes [#1002653](https://www.assembla.com/spaces/scala-ide/tickets/1002653-broken-upgrades-in-the-ide--scala-refactoring-dependency-is-not-versioned/details#)
>  Generate correct version for nightly builds

- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
Tree printing is buggy and in this case it led to an exception because
some synthetic tree of a for comprehension was printed. In order to
avoid the exception we no longer call the tree printing logic at all.
Instead we compare symbols and their names, which leads along the way
to even better performance.
Fix #1002476
-------
Review by @wpopielarski 
There is still whitespace printed at the location where the import was (instead of completely removing the line), I couldn't figure out so far why that is the case. Anyone an idea?
> Avoid tree printing in organize imports logic

- src/main/scala/scala/tools/refactoring/implementations/AddImportStatement.scala
- src/main/scala/scala/tools/refactoring/implementations/MoveClass.scala
- src/main/scala/scala/tools/refactoring/transformation/TreeTransformations.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/MoveClassTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/AddImportStatementTest.scala
This is a similar change to the rename refactoring. The overall idea is
to not depend on any tree transformations when an import is added to a
file. Theoretically, doing any transformations on the tree is the
optimal solution but only if the tree is a concrete syntax tree. The
scalac trees however are abstract syntax trees and therefore don't do
what we want. For the add import refactoring, they remove all the
formatting of the imports, especially removed new lines are a concern.
This commit therefore replaces the tree transformations by generating
textual code changes. This way, the refactoring is only doing a minimal
change, which in our case is to add one or multiple imports. A side
effect is that some functionality is lost but I consider that as a good
change. Formerly, the add import …
> Do not depend on tree transformations for the add import refactoring 

- src/main/scala/scala/tools/refactoring/sourcegen/PrettyPrinter.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
It is kind of difficult to describe why this exception is thrown and the
fact that it took me an entire working day to fix it should speak for
itself. But I will try nevertheless to give a description:
The problem starts in the class `OrganizeImports.AlwaysUseWildcards`. If
the "collapse to wildcard import" option is enabled, this class replaces
all imports that are matched by a wildcard import with such a wildcard
import. Even though the wildcard import is generated it has positions
since the position of the first matching import are set to it. This
means that `ReusingPrinter` is used to print the import. However, in
order to print import selectors the refactoring logic needs to generate
its own trees, called `ImportSelectorTree`. This is necessary, since
import selectors are not trees …
> Do not throw exception when imports are collapsed to wildcard import

- src/main/scala/scala/tools/refactoring/transformation/TreeTransformations.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/MoveClassTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/AddImportStatementTest.scala
This commit is doing two things. For every import that is added, it is
checked that it is surrounded by empty lines if they are necessary.
"Necessary" means that the empty lines are added in two cases: After a
package declaration and before a class declaration. Once an import is
added, a code snippet like the following
package pkg
trait X {
def d: Try[Int]
}
will look like this:
package pkg
import scala.util.Try
trait X {
def d: Try[Int]
}
The added empty lines actually complicate the implementation and are not
needed to fix the problem of the missing import. But they are needed to
ensure consistency in the implementation. If we have a code snippet like
the following
package pkg
trait X {
def d: Try[Int]
}
The question about where to put the import declaration comes up. Shall
it be added …
> Add empty lines around added imports and put import at right location

- patch-ide.bash
- src/main/scala/scala/tools/refactoring/analysis/GlobalIndexes.scala
- src/main/scala/scala/tools/refactoring/analysis/SymbolExpanders.scala
- src/main/scala/scala/tools/refactoring/common/EnrichedTrees.scala
- src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/RefactoringTestSuite.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
This PR implements support for named parameters when doing rename refactorings (see [Ticket #1002501](https://www.assembla.com/spaces/scala-ide/tickets/1002501-rename-does-not-consider-named-parameters/details#), as well as [Ticket #1002572](https://www.assembla.com/spaces/scala-ide/tickets/1002572-rename-refactoring-for-case-class-parameter-should-also-rename-named-arguments-to-apply-and-copy/details#)). To achieve this, this PR takes care of several things:
1. Named parameters are desugared. Therefore we have to manually parse them in the original source code. Unfortunately, due to the compiler setting incorrect positions on some of the trees in the AST, this is harder than it should be. The parsing is done with the `SourceWithMarker` framework, that now supports backtracking (note that …
> Consider named parameters during rename refactorings

- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
@sschaef `Movements.id` now should behave as expected and not match comments any more.
> `Movements.id` must not match comments

- src/main/scala/scala/tools/refactoring/analysis/GlobalIndexes.scala
- src/main/scala/scala/tools/refactoring/common/PositionDebugging.scala
- src/main/scala/scala/tools/refactoring/implementations/MarkOccurrences.scala
- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
And yet another workaround for a position bug of the compiler. Fixes [Ticket #1002651](https://www.assembla.com/spaces/scala-ide/tickets/1002651-rename-breaks-with-interpolated-strings/details#).
> Fix rename for interpolated strings like f"$x"

- src/main/scala/scala/tools/refactoring/analysis/GlobalIndexes.scala
- src/main/scala/scala/tools/refactoring/analysis/SymbolExpanders.scala
- src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
Note that this PR actually makes the implementation simpler, and removes more code than it adds.
Fix [#1002650](https://www.assembla.com/spaces/scala-ide/tickets/1002650-rename-fails-in-for-comprehensions/details#)
> Fix rename in for comprehensions

- src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestRefactoring.scala
This PR takes care of [ticket 1002680](https://www.assembla.com/spaces/scala-ide/tickets/1002680-rename-ignores-arguments-of-annotations) for Scala Annotations. Handling Java annotations properly requires changes to the compiler, as discussed in [ticket 1001793](https://www.assembla.com/spaces/scala-ide/tickets/1001793-rename-and-organize-imports-ignore-arguments-of-annotations).
> Properly Rename Scala Annotation Arguments

- src/main/scala/scala/tools/refactoring/common/tracing.scala
- src/main/scala/scala/tools/refactoring/implementations/MarkOccurrences.scala
- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/analysis/DeclarationIndexTest.scala
- src/test/scala/scala/tools/refactoring/tests/analysis/ImportAnalysisTest.scala
- src/test/scala/scala/tools/refactoring/tests/common/InsertionPositionsTest.scala
- src/test/scala/scala/tools/refactoring/tests/common/SelectionDependenciesTest.scala
- src/test/scala/scala/tools/refactoring/tests/common/SelectionPropertiesTest.scala
- src/test/scala/scala/tools/refactoring/tests/common/SelectionsTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/MarkOccurrencesTest.scala
- src/test/scala/scala/tools/refactoring/tests/transformation/TransformableSelectionTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
- src/test/scala/scala/tools/refactoring/tests/util/TextSelections.scala
- src/test/scala/scala/tools/refactoring/tests/util/TextSelectionsTest.scala
Consult [#1002698](https://app.assembla.com/spaces/scala-ide/tickets/1002698-markoccurences-and-rename-refactoring-should-share-common-implementation-for--quot-find-all-occurences-quot-/details#) as well as the commit messages for further background.
> Implement `Rename` on top of `MarkOccurences`

- src/main/scala/scala/tools/refactoring/analysis/CompilationUnitDependencies.scala
- src/main/scala/scala/tools/refactoring/common/EnrichedTrees.scala
As the ticket shows, `nameString` can throw an exception. The method
should return an Option but I'm to lazy to refactor the code. Also,
using Option everywhere would lead to quite some overhead, I assume the
few cases that throw an exception are the lesser evil.
Fix #1002711
> Swallow exception after nameString call

- src/main/scala/scala/tools/refactoring/util/SourceWithMarker.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceWithMarkerTest.scala
See [ticket 1002674](https://app.assembla.com/spaces/scala-ide/tickets/1002674-cannot-rename-private-var-starting-with---39-_--39-/details#) to understand the problem. Consult the commit messages to comprehend the solution ;-).
> Fix renaming identifiers starting with '_'

- .gitignore
- src/main/scala/scala/tools/refactoring/implementations/MoveClass.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/MoveClassTest.scala
See [#1002786](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002786-move-class-is-mislead-by-types-with-same-name-from-different-packages/details#).
> Be more careful before rewriting imports in `MoveClass` 

- src/main/scala/scala/tools/refactoring/common/Selections.scala
- src/main/scala/scala/tools/refactoring/implementations/MarkOccurrences.scala
- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/main/scala/scala/tools/refactoring/util/SourceHelpers.scala
- src/main/scala/scala/tools/refactoring/util/SourceWithSelection.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/MarkOccurrencesTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/SourceHelpersTest.scala
Self references need special treatment since their representation in typed ASTs is incomplete. This PR takes care of this for `Rename` and `MarkOccurrences`. See [#1002803](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002803-rename-fails-with-self-references/details#) as well as https://github.com/scala-ide/scala-ide/pull/1132.
> Special treatment for self references

- src/main/scala-2.10/scala/tools/refactoring/implementations/oimports/ImplicitValDefTraverserPF.scala
- src/main/scala-2.11/scala/tools/refactoring/implementations/oimports/ImplicitValDefTraverserPF.scala
- src/main/scala-2.12/scala/tools/refactoring/implementations/oimports/ImplicitValDefTraverserPF.scala
- src/main/scala/scala/tools/refactoring/implementations/ImportsHelper.scala
- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/ImportParticipants.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/NotPackageImportParticipants.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/OrganizeImportsWorker.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/RegionTransformations.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/TreeToolbox.scala
- src/test/scala-2.10/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsScalaSpecificTests.scala
- src/test/scala-2.11/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsScalaSpecificTests.scala
- src/test/scala-2.11/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsWithMacrosTest.scala
- src/test/scala-2.12/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsScalaSpecificTests.scala
- src/test/scala-2.12/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsWithMacrosTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsCollapseSelectorsToWildcardTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/PrependOrDropScalaPackageFromRecomputedTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/PrependOrDropScalaPackageKeepTest.scala
This is second (of 3) PR for Organize Imports refactoring 
Changes path dependent types for sake of better
defined responsibilities
OrganizeImports depends on traits like TreeTransformations and so
on but it is not its role to do this sort of job. These things are
push down to OrganizeImportsWorker and its colaborators.
From now all refactored imports are enclosed in regions. And additionally
everywhere if is possible classes depend on `global` directly.
> Changes path dependent types for sake of better defined responsibilities

- src/main/scala/scala/tools/refactoring/analysis/GlobalIndexes.scala
- src/main/scala/scala/tools/refactoring/analysis/Indexes.scala
- src/main/scala/scala/tools/refactoring/analysis/SymbolExpanders.scala
- src/main/scala/scala/tools/refactoring/common/Change.scala
- src/main/scala/scala/tools/refactoring/implementations/MarkOccurrences.scala
- src/main/scala/scala/tools/refactoring/implementations/Rename.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/RenameTest.scala
- src/test/scala/scala/tools/refactoring/tests/util/TestHelper.scala
This PR is dedicated to package renames, that are special for two reasons:
1. Associated package objects must be renamed together with their packages
2. Although not strictly required, package renames typically should be accompanied by associated directory renames
This PR takes care of both issues. Note that up until now there was no `scala.tools.refactoring.common.Change` that models moving files from one directory to another. `scala.tools.refactoring.common.MoveToDirChange` takes care of this. An associated PR for ScalaIDE, that takes advantage of the new API, can be found [here](https://github.com/scala-ide/scala-ide/pull/1140).
Fixes [#1002769](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1002769-package-renaming-error-in-the-package-object/details#).
> Make renaming packages work

- src/main/scala/scala/tools/refactoring/util/SourceHelpers.scala
Problem described in title hits refactoring of Organize Imports for Windows releases.
I need advice to write a test for it.
> Enables including trailing line for Windows line separator

- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/test/scala-2.10/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsScalaSpecificTests.scala
- src/test/scala-2.11/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsScalaSpecificTests.scala
- src/test/scala-2.11/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsWithMacrosTest.scala
- src/test/scala-2.12/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsScalaSpecificTests.scala
- src/test/scala-2.12/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsWithMacrosTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsCollapseSelectorsToWildcardTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsFullyRecomputeTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsGroupsTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsRecomputeAndModifyTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsWildcardsTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/PrependOrDropScalaPackageFromRecomputedTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/PrependOrDropScalaPackageKeepTest.scala
'options' has been removed because it exposed specific scala-refactoring
types outside. It is incorrect especially these types usually depend on
'global'. Configuration should rather be passed with simple scala types.
> Removes options from OrganizeImports

- src/main/scala/scala/tools/refactoring/common/Change.scala
- src/main/scala/scala/tools/refactoring/implementations/OrganizeImports.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/RegionTransformations.scala
- src/main/scala/scala/tools/refactoring/implementations/oimports/TreeToolbox.scala
- src/main/scala/scala/tools/refactoring/sourcegen/Formatting.scala
- src/test/scala/scala/tools/refactoring/tests/RefactoringTestSuite.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsBaseTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsEndOfLineTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsFullyRecomputeTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsRecomputeAndModifyTest.scala
- src/test/scala/scala/tools/refactoring/tests/implementations/imports/OrganizeImportsTest.scala
additionally this implementation protects against Array Index Out Of
Bounds Exception for following code:
```scala
package a
import c.b.A
```
which should be tailored to
```scala
package a
```
> Reorganized imports preserve existing end of line

- build.sbt
- src/test/scala/scala/tools/refactoring/tests/implementations/ExplicitGettersSettersTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/PrettyPrinterTest.scala
- src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceGenTest.scala
Tree printing dependent refactorings are still broken on 2.12, as described in #180
> 2.12.2 support
